apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-html
  namespace: html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-html
  template:
    metadata:
      labels:
        app: message-html
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          gitRepo:
            repository: https://github.com/OzgeanGit/messageHtml.git
            revision: main
            directory: .
